// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	model "example-tasks/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// MockTaskRepository is an autogenerated mock type for the TaskRepository type
type MockTaskRepository struct {
	mock.Mock
}

type MockTaskRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskRepository) EXPECT() *MockTaskRepository_Expecter {
	return &MockTaskRepository_Expecter{mock: &_m.Mock}
}

// CreateTask provides a mock function with given fields: task
func (_m *MockTaskRepository) CreateTask(task model.TaskRequest) (string, error) {
	ret := _m.Called(task)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(model.TaskRequest) (string, error)); ok {
		return rf(task)
	}
	if rf, ok := ret.Get(0).(func(model.TaskRequest) string); ok {
		r0 = rf(task)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(model.TaskRequest) error); ok {
		r1 = rf(task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskRepository_CreateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTask'
type MockTaskRepository_CreateTask_Call struct {
	*mock.Call
}

// CreateTask is a helper method to define mock.On call
//   - task model.TaskRequest
func (_e *MockTaskRepository_Expecter) CreateTask(task interface{}) *MockTaskRepository_CreateTask_Call {
	return &MockTaskRepository_CreateTask_Call{Call: _e.mock.On("CreateTask", task)}
}

func (_c *MockTaskRepository_CreateTask_Call) Run(run func(task model.TaskRequest)) *MockTaskRepository_CreateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TaskRequest))
	})
	return _c
}

func (_c *MockTaskRepository_CreateTask_Call) Return(_a0 string, _a1 error) *MockTaskRepository_CreateTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskRepository_CreateTask_Call) RunAndReturn(run func(model.TaskRequest) (string, error)) *MockTaskRepository_CreateTask_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTask provides a mock function with given fields: id
func (_m *MockTaskRepository) DeleteTask(id int64) (string, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (string, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int64) string); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskRepository_DeleteTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTask'
type MockTaskRepository_DeleteTask_Call struct {
	*mock.Call
}

// DeleteTask is a helper method to define mock.On call
//   - id int64
func (_e *MockTaskRepository_Expecter) DeleteTask(id interface{}) *MockTaskRepository_DeleteTask_Call {
	return &MockTaskRepository_DeleteTask_Call{Call: _e.mock.On("DeleteTask", id)}
}

func (_c *MockTaskRepository_DeleteTask_Call) Run(run func(id int64)) *MockTaskRepository_DeleteTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockTaskRepository_DeleteTask_Call) Return(_a0 string, _a1 error) *MockTaskRepository_DeleteTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskRepository_DeleteTask_Call) RunAndReturn(run func(int64) (string, error)) *MockTaskRepository_DeleteTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskByID provides a mock function with given fields: id
func (_m *MockTaskRepository) GetTaskByID(id int64) (model.Task, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskByID")
	}

	var r0 model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (model.Task, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int64) model.Task); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(model.Task)
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskRepository_GetTaskByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskByID'
type MockTaskRepository_GetTaskByID_Call struct {
	*mock.Call
}

// GetTaskByID is a helper method to define mock.On call
//   - id int64
func (_e *MockTaskRepository_Expecter) GetTaskByID(id interface{}) *MockTaskRepository_GetTaskByID_Call {
	return &MockTaskRepository_GetTaskByID_Call{Call: _e.mock.On("GetTaskByID", id)}
}

func (_c *MockTaskRepository_GetTaskByID_Call) Run(run func(id int64)) *MockTaskRepository_GetTaskByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockTaskRepository_GetTaskByID_Call) Return(_a0 model.Task, _a1 error) *MockTaskRepository_GetTaskByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskRepository_GetTaskByID_Call) RunAndReturn(run func(int64) (model.Task, error)) *MockTaskRepository_GetTaskByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTasks provides a mock function with given fields: cursor, size, priority, sortWith, sortBy
func (_m *MockTaskRepository) GetTasks(cursor int64, size int, priority int, sortWith string, sortBy string) ([]model.Task, error) {
	ret := _m.Called(cursor, size, priority, sortWith, sortBy)

	if len(ret) == 0 {
		panic("no return value specified for GetTasks")
	}

	var r0 []model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, int, int, string, string) ([]model.Task, error)); ok {
		return rf(cursor, size, priority, sortWith, sortBy)
	}
	if rf, ok := ret.Get(0).(func(int64, int, int, string, string) []model.Task); ok {
		r0 = rf(cursor, size, priority, sortWith, sortBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, int, int, string, string) error); ok {
		r1 = rf(cursor, size, priority, sortWith, sortBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskRepository_GetTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTasks'
type MockTaskRepository_GetTasks_Call struct {
	*mock.Call
}

// GetTasks is a helper method to define mock.On call
//   - cursor int64
//   - size int
//   - priority int
//   - sortWith string
//   - sortBy string
func (_e *MockTaskRepository_Expecter) GetTasks(cursor interface{}, size interface{}, priority interface{}, sortWith interface{}, sortBy interface{}) *MockTaskRepository_GetTasks_Call {
	return &MockTaskRepository_GetTasks_Call{Call: _e.mock.On("GetTasks", cursor, size, priority, sortWith, sortBy)}
}

func (_c *MockTaskRepository_GetTasks_Call) Run(run func(cursor int64, size int, priority int, sortWith string, sortBy string)) *MockTaskRepository_GetTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(int), args[2].(int), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockTaskRepository_GetTasks_Call) Return(_a0 []model.Task, _a1 error) *MockTaskRepository_GetTasks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskRepository_GetTasks_Call) RunAndReturn(run func(int64, int, int, string, string) ([]model.Task, error)) *MockTaskRepository_GetTasks_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTask provides a mock function with given fields: id, task
func (_m *MockTaskRepository) UpdateTask(id int64, task model.TaskRequest) (string, error) {
	ret := _m.Called(id, task)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, model.TaskRequest) (string, error)); ok {
		return rf(id, task)
	}
	if rf, ok := ret.Get(0).(func(int64, model.TaskRequest) string); ok {
		r0 = rf(id, task)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int64, model.TaskRequest) error); ok {
		r1 = rf(id, task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskRepository_UpdateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTask'
type MockTaskRepository_UpdateTask_Call struct {
	*mock.Call
}

// UpdateTask is a helper method to define mock.On call
//   - id int64
//   - task model.TaskRequest
func (_e *MockTaskRepository_Expecter) UpdateTask(id interface{}, task interface{}) *MockTaskRepository_UpdateTask_Call {
	return &MockTaskRepository_UpdateTask_Call{Call: _e.mock.On("UpdateTask", id, task)}
}

func (_c *MockTaskRepository_UpdateTask_Call) Run(run func(id int64, task model.TaskRequest)) *MockTaskRepository_UpdateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(model.TaskRequest))
	})
	return _c
}

func (_c *MockTaskRepository_UpdateTask_Call) Return(_a0 string, _a1 error) *MockTaskRepository_UpdateTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskRepository_UpdateTask_Call) RunAndReturn(run func(int64, model.TaskRequest) (string, error)) *MockTaskRepository_UpdateTask_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskRepository creates a new instance of MockTaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskRepository {
	mock := &MockTaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
