// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	model "example-tasks/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// MockTaskService is an autogenerated mock type for the TaskService type
type MockTaskService struct {
	mock.Mock
}

type MockTaskService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskService) EXPECT() *MockTaskService_Expecter {
	return &MockTaskService_Expecter{mock: &_m.Mock}
}

// CreateTask provides a mock function with given fields: task
func (_m *MockTaskService) CreateTask(task model.TaskRequest) error {
	ret := _m.Called(task)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.TaskRequest) error); ok {
		r0 = rf(task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskService_CreateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTask'
type MockTaskService_CreateTask_Call struct {
	*mock.Call
}

// CreateTask is a helper method to define mock.On call
//   - task model.TaskRequest
func (_e *MockTaskService_Expecter) CreateTask(task interface{}) *MockTaskService_CreateTask_Call {
	return &MockTaskService_CreateTask_Call{Call: _e.mock.On("CreateTask", task)}
}

func (_c *MockTaskService_CreateTask_Call) Run(run func(task model.TaskRequest)) *MockTaskService_CreateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.TaskRequest))
	})
	return _c
}

func (_c *MockTaskService_CreateTask_Call) Return(_a0 error) *MockTaskService_CreateTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskService_CreateTask_Call) RunAndReturn(run func(model.TaskRequest) error) *MockTaskService_CreateTask_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTask provides a mock function with given fields: id
func (_m *MockTaskService) DeleteTask(id int64) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskService_DeleteTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTask'
type MockTaskService_DeleteTask_Call struct {
	*mock.Call
}

// DeleteTask is a helper method to define mock.On call
//   - id int64
func (_e *MockTaskService_Expecter) DeleteTask(id interface{}) *MockTaskService_DeleteTask_Call {
	return &MockTaskService_DeleteTask_Call{Call: _e.mock.On("DeleteTask", id)}
}

func (_c *MockTaskService_DeleteTask_Call) Run(run func(id int64)) *MockTaskService_DeleteTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockTaskService_DeleteTask_Call) Return(_a0 error) *MockTaskService_DeleteTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskService_DeleteTask_Call) RunAndReturn(run func(int64) error) *MockTaskService_DeleteTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskByID provides a mock function with given fields: id
func (_m *MockTaskService) GetTaskByID(id int64) (model.Task, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskByID")
	}

	var r0 model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (model.Task, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int64) model.Task); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(model.Task)
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskService_GetTaskByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskByID'
type MockTaskService_GetTaskByID_Call struct {
	*mock.Call
}

// GetTaskByID is a helper method to define mock.On call
//   - id int64
func (_e *MockTaskService_Expecter) GetTaskByID(id interface{}) *MockTaskService_GetTaskByID_Call {
	return &MockTaskService_GetTaskByID_Call{Call: _e.mock.On("GetTaskByID", id)}
}

func (_c *MockTaskService_GetTaskByID_Call) Run(run func(id int64)) *MockTaskService_GetTaskByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockTaskService_GetTaskByID_Call) Return(_a0 model.Task, _a1 error) *MockTaskService_GetTaskByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskService_GetTaskByID_Call) RunAndReturn(run func(int64) (model.Task, error)) *MockTaskService_GetTaskByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTasks provides a mock function with given fields: cursor, size, priority, sortWith, sortBy
func (_m *MockTaskService) GetTasks(cursor int64, size int, priority int, sortWith string, sortBy string) (*model.PagedResponse, error) {
	ret := _m.Called(cursor, size, priority, sortWith, sortBy)

	if len(ret) == 0 {
		panic("no return value specified for GetTasks")
	}

	var r0 *model.PagedResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, int, int, string, string) (*model.PagedResponse, error)); ok {
		return rf(cursor, size, priority, sortWith, sortBy)
	}
	if rf, ok := ret.Get(0).(func(int64, int, int, string, string) *model.PagedResponse); ok {
		r0 = rf(cursor, size, priority, sortWith, sortBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PagedResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, int, int, string, string) error); ok {
		r1 = rf(cursor, size, priority, sortWith, sortBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskService_GetTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTasks'
type MockTaskService_GetTasks_Call struct {
	*mock.Call
}

// GetTasks is a helper method to define mock.On call
//   - cursor int64
//   - size int
//   - priority int
//   - sortWith string
//   - sortBy string
func (_e *MockTaskService_Expecter) GetTasks(cursor interface{}, size interface{}, priority interface{}, sortWith interface{}, sortBy interface{}) *MockTaskService_GetTasks_Call {
	return &MockTaskService_GetTasks_Call{Call: _e.mock.On("GetTasks", cursor, size, priority, sortWith, sortBy)}
}

func (_c *MockTaskService_GetTasks_Call) Run(run func(cursor int64, size int, priority int, sortWith string, sortBy string)) *MockTaskService_GetTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(int), args[2].(int), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockTaskService_GetTasks_Call) Return(_a0 *model.PagedResponse, _a1 error) *MockTaskService_GetTasks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskService_GetTasks_Call) RunAndReturn(run func(int64, int, int, string, string) (*model.PagedResponse, error)) *MockTaskService_GetTasks_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTask provides a mock function with given fields: id, task
func (_m *MockTaskService) UpdateTask(id int64, task model.TaskRequest) error {
	ret := _m.Called(id, task)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, model.TaskRequest) error); ok {
		r0 = rf(id, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskService_UpdateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTask'
type MockTaskService_UpdateTask_Call struct {
	*mock.Call
}

// UpdateTask is a helper method to define mock.On call
//   - id int64
//   - task model.TaskRequest
func (_e *MockTaskService_Expecter) UpdateTask(id interface{}, task interface{}) *MockTaskService_UpdateTask_Call {
	return &MockTaskService_UpdateTask_Call{Call: _e.mock.On("UpdateTask", id, task)}
}

func (_c *MockTaskService_UpdateTask_Call) Run(run func(id int64, task model.TaskRequest)) *MockTaskService_UpdateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(model.TaskRequest))
	})
	return _c
}

func (_c *MockTaskService_UpdateTask_Call) Return(_a0 error) *MockTaskService_UpdateTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskService_UpdateTask_Call) RunAndReturn(run func(int64, model.TaskRequest) error) *MockTaskService_UpdateTask_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskService creates a new instance of MockTaskService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskService {
	mock := &MockTaskService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
